.PHONY: clean

Figure-1-B.tree: ../data/phylogeny/bac120_r95.tree ../data/phylogeny/Lineage_of_32_sp.xlsx ../.venv/bin/activate
	source ../.venv/bin/activate && python Figure_1_B.py

clean:
	rm -f Figure-1-B.tree
